arm_groups:
  target:
    entity:
      integration: diagral
      domain: alarm_control_panel
  fields:
    group_ids:
      example: "[3,2] or 3"
      required: true
      selector:
        object:

disarm_groups:
  target:
    entity:
      integration: diagral
      domain: alarm_control_panel
  fields:
    group_ids:
      example: "[3,2] or 3"
      required: true
      selector:
        object:

register_webhook:
  target:
    entity:
      integration: diagral
      domain: alarm_control_panel

unregister_webhook:
  target:
    entity:
      integration: diagral
      domain: alarm_control_panel
